### PR TITLE
Correctly identify parent label on contextual-images

### PR DESCRIPTION
**Pull request by gvc**
## What's the purpose of this pull request?

The Guide on how to use different images in different contexts wasn't showing up on our docs though it was accessible directly through the URL. This PR aims to fix it :)

## How to Test It

Go to our docs preview and try to find the link on the navigation.

### CODE REVIEW

**Comment by hellofanny** [comment]
@gvc guilaaa, this [preview](https://faststore-site-git-fix-contextual-images-label-faststore.vercel.app/docs) still not showing this page in the Menu navigation. I think it's a cache issue, I re-deployed the main in vercel to test, and the page is appearing in the menu. 😕 

Can you double-check if everything is okay? https://www.faststore.dev/docs 

image

**Review by eduardoformiga — APPROVED** [review]
that's a known cache issue that @hellofanny mentioned. ✨

**Comment by hellofanny** [comment]
@gvc do you think we can close this PR? 👀

**Comment by gvc** [comment]
Sorry, Fan! Missed this conversation!

**Pull request closed without merging**
