### PR TITLE
BREAKING CHANGE: Remove deprecated folders

### PR DESCRIPTION
**Pull request by tlgimenes**
## What's the purpose of this pull request?
This PR removes deprecated folders as this issue requested
https://github.com/vtex/faststore/issues/920

## How it works? 
We are still in alpha. Let's use this time to remove all deprecated folders. From now on, the old state will be on the branch `legacy`.
Also, this PR shrinks the store-ui size to 10Kb max

## How to test it?
I've upgraded our base.store to work with this
https://github.com/vtex-sites/base.store/pull/20

### CODE REVIEW

**Comment by heynemann** [comment]
Won't this break all our stores?

**Comment by tlgimenes** [comment]
> Won't this break all our stores?

They won't be able to upgrade to the latest version anymore. That's ok for now I guess because it will allow us to develop our starters faster

**Comment by emersonlaurentino** [comment]
Should we create a deprecated branch to continue maintaining (bug fix) or just let it go?

**Comment by tlgimenes** [comment]
> Should we create a deprecated branch to continue maintaining (bug fix) or just let it go?

yes! we are creating a `legacy` branch

**Review by emersonlaurentino — APPROVED** [review]

**Pull request merged**
