### PR TITLE
fix: pickBestSku instead of first sku in products query

### PR DESCRIPTION
**Pull request by eduardoformiga**
## What's the purpose of this pull request?

Address this issue
- https://github.com/vtex/faststore/issues/2132

## How it works?

While in search Page and PLP, FastStore API products search query was getting always the first `item` (sku) from the `product.items`. In this case, we should get the best item (item available with smallest value).

|Before|After|
|-|-|
|Screenshot 2023-11-30 at 19 29 12|Screenshot 2023-11-30 at 19 27 11|

## How to test it?

Check the preview link from starters store, with the tests mentioned [in the issue](https://github.com/vtex/faststore/issues/2132).

### Starters Deploy Preview

Preview 
- https://sfj-4b57e5c--starter.preview.vtex.app/
- https://github.com/vtex-sites/starter.store/pull/292

## References
- https://help.vtex.com/pt/tutorial/ordenando-imagens-na-vitrine-e-na-pagina-de-produto--tutorials_278
- https://storeframework.myvtex.com/api/io/_v/api/intelligent-search/product_search/trade-policy/1/?hideUnavailableItems=true&q=Apple%20Magic%20Mouse

### CODE REVIEW

**Review by hellofanny — APPROVED** [review]

**Comment by victors1682** [comment]
Before 
Screenshot 2023-12-01 at 9 15 52 AM
After
Screenshot 2023-12-01 at 9 16 45 AM

looking good! thanks 🚀

**Review by icazevedo — APPROVED** [review]
LGTM. WDYT of changing line 49 as well to apply the same fix to Top Search results?

**Comment by eduardoformiga** [comment]
> LGTM. WDYT of changing line 49 as well to apply the same fix to Top Search results?

good catch!
done [here](https://github.com/vtex/faststore/pull/2136/commits/988d00af91b67cb583c02f867138bbd7bc2ef5d7).

**Review by icazevedo — APPROVED** [review]

**Comment by eduardoformiga** [comment]
after some discussion with the team, we understand that this PR addressed better the issue.

**Pull request merged**
