### PR TITLE
revert: evergreen documentation

### PR DESCRIPTION
**Pull request by emersonlaurentino**
## What's the purpose of this pull request?

All documentation about evergreen must be in `/apps/site` avoid `/apps/docs`. ref https://github.com/vtex/faststore/pull/1561

## How it works?

Revert all commits in this specific folder.

### CODE REVIEW

**Review by eduardoformiga — APPROVED** [review]
LGTM! 
Looks the same as before evergreen.

**Comment by hellofanny** [comment]
We need to remove the SROnly component [page](https://faststore-git-revert-docs-evergreen-faststore.vercel.app/reference/ui/atoms/SROnly)
image

**Comment by hellofanny** [comment]
We also need to remove the pages listed below: 🥺 

- [BuyButton](https://faststore-git-revert-docs-evergreen-faststore.vercel.app/reference/ui/molecules/BuyButton)
- [CheckboxField](https://faststore-git-revert-docs-evergreen-faststore.vercel.app/reference/ui/molecules/CheckboxField)
- [DiscountBadge](https://faststore-git-revert-docs-evergreen-faststore.vercel.app/reference/ui/molecules/DiscountBadge)
- [InputField](https://faststore-git-revert-docs-evergreen-faststore.vercel.app/reference/ui/molecules/InputField)
- [LinkButton](https://faststore-git-revert-docs-evergreen-faststore.vercel.app/reference/ui/molecules/LinkButton)
- [RadioField](https://faststore-git-revert-docs-evergreen-faststore.vercel.app/reference/ui/molecules/RadioField)
- [SelectField](https://faststore-git-revert-docs-evergreen-faststore.vercel.app/reference/ui/molecules/SelectField)
- [Toggle](https://faststore-git-revert-docs-evergreen-faststore.vercel.app/reference/ui/molecules/Toggle)
- [ToggleField](https://faststore-git-revert-docs-evergreen-faststore.vercel.app/reference/ui/molecules/ToggleField)

**Review by hellofanny — CHANGES_REQUESTED** [review]
Niceeeee! Can you also remove the pages listed below: 🥺 

- [BuyButton](https://faststore-git-revert-docs-evergreen-faststore.vercel.app/reference/ui/molecules/BuyButton)
- [CheckboxField](https://faststore-git-revert-docs-evergreen-faststore.vercel.app/reference/ui/molecules/CheckboxField)
- [DiscountBadge](https://faststore-git-revert-docs-evergreen-faststore.vercel.app/reference/ui/molecules/DiscountBadge)
- [InputField](https://faststore-git-revert-docs-evergreen-faststore.vercel.app/reference/ui/molecules/InputField)
- [LinkButton](https://faststore-git-revert-docs-evergreen-faststore.vercel.app/reference/ui/molecules/LinkButton)
- [RadioField](https://faststore-git-revert-docs-evergreen-faststore.vercel.app/reference/ui/molecules/RadioField)
- [SelectField](https://faststore-git-revert-docs-evergreen-faststore.vercel.app/reference/ui/molecules/SelectField)
- [Toggle](https://faststore-git-revert-docs-evergreen-faststore.vercel.app/reference/ui/molecules/Toggle)
- [ToggleField](https://faststore-git-revert-docs-evergreen-faststore.vercel.app/reference/ui/molecules/ToggleField)

**Comment by eduardoformiga** [comment]
> Niceeeee! Can you also remove the pages listed below: 🥺
> 
> * [BuyButton](https://faststore-git-revert-docs-evergreen-faststore.vercel.app/reference/ui/molecules/BuyButton)
> * [CheckboxField](https://faststore-git-revert-docs-evergreen-faststore.vercel.app/reference/ui/molecules/CheckboxField)
> * [DiscountBadge](https://faststore-git-revert-docs-evergreen-faststore.vercel.app/reference/ui/molecules/DiscountBadge)
> * [InputField](https://faststore-git-revert-docs-evergreen-faststore.vercel.app/reference/ui/molecules/InputField)
> * [LinkButton](https://faststore-git-revert-docs-evergreen-faststore.vercel.app/reference/ui/molecules/LinkButton)
> * [RadioField](https://faststore-git-revert-docs-evergreen-faststore.vercel.app/reference/ui/molecules/RadioField)
> * [SelectField](https://faststore-git-revert-docs-evergreen-faststore.vercel.app/reference/ui/molecules/SelectField)
> * [Toggle](https://faststore-git-revert-docs-evergreen-faststore.vercel.app/reference/ui/molecules/Toggle)
> * [ToggleField](https://faststore-git-revert-docs-evergreen-faststore.vercel.app/reference/ui/molecules/ToggleField)

Nice catch!

**Comment by emersonlaurentino** [comment]
@hellofanny I revert to this commit https://github.com/vtex/faststore/commit/6743690f41d38a7f6a1060f541775c8a6f82e2f5 that is the commit before we make any change from evergreen.

**Comment by hellofanny** [comment]
> @hellofanny I revert to this commit [6743690](https://github.com/vtex/faststore/commit/6743690f41d38a7f6a1060f541775c8a6f82e2f5) that is the commit before we make any change from evergreen.

I think it should be the previously one. Isn't this [one](https://github.com/vtex/faststore/commit/82a6325bd801a6c3a36a2d2aa294ea36a5e9b18d)?

**Pull request closed without merging**
