### PR TITLE
fix(api): Prevent throw error, when skus is empty

### PR DESCRIPTION
**Pull request by igorbrasileiro**
## What's the purpose of this pull request?
Prevent throw error when SKUs is empty, also missingSkus will be empty.

### CODE REVIEW

**Review by filipewl — APPROVED** [review]

**Review by eduardoformiga — CHANGES_REQUESTED** [review]
I tested it simulating the error and I think it's not working as expected since we won't have the missing SKUs on the error message.
`"message": "Search API did not return the following skus: ",`

Logs from the main local variables:
Screen Shot 2022-04-08 at 12 58 15

So I have a suggestion:

1. Maps the `skus` object as a key/value object.
```javascript
const skus = skuIds.map((skuId) => ({
      key: skuId,
      value: skuBySkuId[skuId],
    }))
```

2. The `missingSkus` mapping the new key (sku).
```javascript
const missingSkus = skus.filter((sku) => !sku.value).map((sku) => sku.key)
```

3. Keeps the original  if and return the `skus` values:
```js
if (missingSkus.length > 0) {
//...
}

return skus.map((sku) => sku.value)
```

logs after changes:
Screen Shot 2022-04-08 at 13 10 48

error message:
`"message": "Search API did not return the following skus: 1010",`


We can pair programming to discuss more :)

**Comment by igorbrasileiro** [comment]
> I tested it simulating the error and I think it's not working as expected since we won't have the missing SKUs on the error message. `"message": "Search API did not return the following skus: ",`
> 
> Logs from the main local variables: Screen Shot 2022-04-08 at 12 58 15
> 
> So I have a suggestion:
> 
> 1. Maps the `skus` object as a key/value object.
> 
> ```js
> const skus = skuIds.map((skuId) => ({
>       key: skuId,
>       value: skuBySkuId[skuId],
>     }))
> ```
> 
> 2. The `missingSkus` mapping the new key (sku).
> 
> ```js
> const missingSkus = skus.filter((sku) => !sku.value).map((sku) => sku.key)
> ```
> 
> 3. Keeps the original  `if` and return the `skus` values:
> 
> ```js
> if (missingSkus.length > 0) {
> //...
> }
> 
> return skus.map((sku) => sku.value)
> ```
> 
> logs after changes: Screen Shot 2022-04-08 at 13 10 48
> 
> error message: `"message": "Search API did not return the following skus: 1010",`
> 
> We can pair programming to discuss more :)

Your change doesn't fix the problem, fix the error message. Yeah, I can fix the error message too. Thank you

**Comment by igorbrasileiro** [comment]
@eduardoformiga do you still think this change is necessary since now we're not using the checkout simulation?

**Comment by eduardoformiga** [comment]
> @eduardoformiga do you still think this change is necessary since now we're not using the checkout simulation?

I think we are using the `skuLoader` in other places than the checkout simulation. Like in the `product` Query resolver, and the `validateCart` (image below). So it would be great to have the error message logging as expected, with the correct skus. But we can address it afterward as well. What do you think?


Screen Shot 2022-05-23 at 17 35 26

**Pull request closed without merging**
