### PR TITLE
Feat: Add params sponsoredCount query search

### PR DESCRIPTION
**Pull request by sanderpaniago**
## What's the purpose of this pull request?

Implement the sponsoredCount parameter in the search query, making it possible to control the number of sponsored products returned.

## How it works?

A new non-mandatory parameter has been added to the search querry called sponsoredCount, which you just need to set when calling the querry:
```js
query {
  search(first: 12, sponsoredCount: 5) {
    products {
      edges {
        node {
          isVariantOf {
            name
          }
          advertisement {
            adId
            campaignId
            actionCost
            adResponseId
          }
        }
      }
    }
  }
}
```
## Checklist

<em>You may erase this after checking them all :wink:</em>

**PR Title and Commit Messages**

- [ ] PR title and commit messages follow the [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/) specification
  - Available prefixes: `feat`, `fix`, `chore`, `docs`, `style`, `refactor` and `test`

**PR Description**

- [ ] Added a label according to the PR goal - `breaking change`, `bug`, `contributing`, `performance`, `documentation`..

**Dependencies**

- [ ] Committed the `yarn.lock` file when there were changes to the packages

### CODE REVIEW

**Comment by pedromtec** [comment]
@sanderpaniago. The CI is failing.  I think you need to update the unit tests.

**Comment by sanderpaniago** [comment]
@pedromtec  resolvido o erro no CI

**Comment by gvc** [comment]
How will our customers set the `sponsoredCount`? From what I've seen in the code it's only possible via an override?

**Comment by sanderpaniago** [comment]
It will be a parameter passed in the search query

**Review by pedromtec — APPROVED** [review]
The code looks good to me. I have a question **(non-blocking)** . At what point does this parameter go to the query string? Will this be done in another PR?

**Comment by sanderpaniago** [comment]
It will be sent in the search query, but at the moment I have not configured a fastStore component to send this parameter, this functionality is to enable a feature that is being implemented in fastShop

**Pull request merged**
