### PR TITLE
Chore: rename queries and fragments

### PR DESCRIPTION
**Pull request by eduardoformiga**
## What's the purpose of this pull request?

This PR aims to rename queries and fragments to prevent confusion while Extending the FastStore API.

|before|after|
|-|-|
|ServerProductPage|ServerProduct|
|ClientProducts|ClientManyProducts|

### CODE REVIEW

**Comment by emersonlaurentino** [comment]
Avoid `single` and `multiple`. Why don't we use `unique` and `many`as well as ORM tools on the market?

**Comment by gvc** [comment]
After a little thought, I think we are adding unnecessary complexity to try to fix some problem that has not yet manifested, AFAIK.

I think that the complexity we're adding for every developer to try to remember out if it is Single, Unique or Many or Multiple is greater than the debugging complexity of trying to figure out if they made a typo.

TL:DR; I think we should leave things as they are and close this PR.

**Comment by icazevedo** [comment]
> After a little thought, I think we are adding unnecessary complexity to try to fix some problem that has not yet manifested, AFAIK.
> 
> I think that the complexity we're adding for every developer to try to remember out if it is Single, Unique or Many or Multiple is greater than the debugging complexity of trying to figure out if they made a typo.
> 
> TL:DR; I think we should leave things as they are and close this PR.

I disagree with your conclusion. I don't think the complexity would be too much. What makes me unconfortable to change this once the problem appears is that it would break the API contract to change the name.

**Comment by eduardoformiga** [comment]
> Avoid `single` and `multiple`. Why don't we use `unique` and `many`as well as ORM tools on the market?

Let's go with Many instead of multiple and nothing when is single? WDYT? @emersonlaurentino

**Review by emersonlaurentino — APPROVED** [review]

**Comment by emersonlaurentino** [comment]
for the future: this is the kind of thing that should have been previously addressed in the RFC.

**Review by icazevedo — APPROVED** [review]
LGTM

**Pull request merged**
